[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_markets = "9Q1skR94bjCuBmX78H2MXuefMLqPsgXEzrGBN1pRUtRT"

[programs.localnet]
private_markets = "FxUZ9r65C8RJDSuHSmiryVWUx9ffeWAX9392iuHCxKr7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=cac5129f-2030-484b-b9c9-6776f80ce9e7"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Bv3Fb9VjzjWGfX18QTUcVycAfeLoQ5zZN6vv2g3cTZxp"
program = "/Users/ayush/Documents/hackathons/cyberpunk/artifacts/arcium_program_0.4.0.so"

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899
